### ISSUE TITLE
sir help

### ISSUE THREAD

**Issue by xpaperjamx** [TehSeph/ToS-Addons#3]
i tried the item color addon and its good, sir can i ask u a question? how to pull variables which game uses? like stat.hp which get hp value? i want to write a script which change mobs name color and always show mobs name so that i could easy saw the mobs during hunting session tnx

**Comment by TehSeph** [comment]
There is a nice tutorial for getting started in the [tutorial repo hosted here](https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/wiki).

As for figuring out what table contains what functions... There is no simple answer. You just have to learn by looking at the official IMC code and seeing what they used. Hopefully in the future us devs can make a sort of addon api, but until then [find](http://ss64.com/nt/find.html) / [grep](http://www.gnu.org/software/grep/manual/grep.html) is your best friend.
